server:
  port: 8083

spring:
  application:
    name: pedidos-core

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect

  datasource:
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/pedido_core
    username: jeanfernandes
    password: admin
    driveClassName: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

apis:
  produto_query: http://localhost:8080/produtos
  produto_core: http://localhost:8081/produto