server:
  port: 8080

spring:
  application:
    name: produtos-query

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect

  datasource:
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/produto_query
    username: jeanfernandes
    password: admin
    driveClassName: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest